# application.yml
server:
  port: 8761

spring:
  application:
    name: ecommerce-service-registry  # Must match your config repo file name # This is the service name to register in Eureka and Unique Service Name in the network
  profiles:
    active: dev
#  config:
#    import: optional:configserver:http://localhost:8888  # Config Server URL


# Eureka server-specific configuration
eureka:
  client:
    register-with-eureka: false # Service Registry doesn't register itself  # This service itself will not register (it's a registry)
    fetch-registry: false  # Service Registry doesn't fetch services # No need to fetch registry as it is the server
  server:
    enable-self-preservation: false # For development only
    wait-time-in-ms-when-sync-empty: 0 # No delay while starting Eureka server

# Optional: To enable dashboard access
management:
  endpoints:
    web:
      exposure:
        include: "*" # Enable all actuator endpoints

