spring:
  application:
    name: ecommerce-api-gateway

  profiles:
    active: dev  # 🟢 Change this one to dev, uat, prod as needed

  config:
    import:
      - optional:configserver:http://localhost:8888
      - optional:configserver:http://localhost:8888/jwt-secrets







